name: train
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Train model
        run: |
          pip3 install -r requirements.txt
          python train.py
          # Create CML report
          cat metrics.txt >> report.md
          cml send-comment report.md